language: node_js
node_js:
  - '8'
services:
  - xvfb
cache:
  npm: true
  directories:
    - node_modules
before_install:
  - npm i -g npm@6.4.1
script:
  - npm run build
  - npm run lint
  - npm run test
